name: Format and Lint

permissions:
  pull-requests: write
  contents: write
  actions: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  create:
  workflow_dispatch:

env:
  NODE_VERSION: '20'
  PYTHON_VERSION: '3.12'

jobs:
  format-and-lint:
    name: Format & Lint
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    strategy:
      matrix:
        language: [python, javascript]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        if: matrix.language == 'python'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set up Node.js
        if: matrix.language == 'javascript'
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Python tools
        if: matrix.language == 'python'
        run: |
           python -m pip install --upgrade pip
           pip install black ruff

      - name: Install JavaScript tools
        if: matrix.language == 'javascript'
        run: npm install

      - name: Run Formatting and Linting for Python
        if: matrix.language == 'python'
        run: |
          npm run format:py
          npm run lint:py

      - name: Run Formatting and Linting for JavaScript
        if: matrix.language == 'javascript'
        run: |
          npm run format:js || true
          npm run lint:js || true

      - name: Commit changes
        run: |
          git config --local user.name "actions-user"
          git config --local user.email "actions-user@example.com"
          git add -A
          if [[ -n $(git status --porcelain) ]]; then
            git commit -m "style: apply formatting and linting" -m "Formatted with Prettier/Black and linted with ESLint/Ruff" --author="Diana-Cl <135276904+Diana-Cl@users.noreply.github.com>"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
